### ISSUE TITLE
"barr" pressure units?

### ISSUE THREAD

**Issue by zhuwenli0723** [jewettaij/moltemplate#100]
In example “https://github.com/jewettaij/moltemplate/tree/e8dd1ce3bbeb98124fd37b3140e7d94f967608ac/examples/all_atom/force_field_OPLSAA/ethylene%2Bbenzene” (and this is the first example I read)..
The generated “system.in.init” indicated that the unit is the “real”, so the pressure unit should be “atmospheres”.
However, in the “run.in.npt”:
```
# Run a short simulation using a Langevin thermostat (for improved stability).
fix fxlan all langevin  300.0 300.0  120  123456  # temp: 300 K
fix fxnph all nph  iso 150.0 150.0 1000.0   # pressure: 150 barr
```
It uses the “barr” as the pressure unit. Should this be a mistake or is there something I am missing?
Thank you so much and your great work!

**Comment by zhuwenli0723** [comment]
oh, I got it.1 bar~=0.9869 atm...

**Comment by jewettaij** [comment]
Hi zhuwenli0723.  Thanks for the correction.
There's a lot of comments in these examples that need to be cleaned up.
When I get a chance to update these examples, I'll include this correction as well ("barr"->"atm").

**Comment by jewettaij** [comment]
I'll close it once I've updated the examples.
