### ISSUE TITLE
oplsaa.lt type 93 is from methylbenzene, not ethylbenzene

### ISSUE THREAD

**Issue by srtee** [jewettaij/moltemplate#101]
In this line:

https://github.com/jewettaij/moltemplate/blob/e8dd1ce3bbeb98124fd37b3140e7d94f967608ac/moltemplate/force_fields/oplsaa.lt#L149

type 93 has the appropriate partial charge for the _methylbenzene_ (or toluene) methyl carbon, not the ethylbenzene methyl carbon. BOSS 4.9's manual has that partial charge listed for CH3 of toluene (https://zarbi.chem.yale.edu/doc/boss49.pdf, page 67).

This is the tiniest of typos _and_ it is inherited from the original TINKER file comments, but I'm hoping you can fix this in Moltemplate's `oplsaa.lt` at least. There's no way that partial charge works for ethylbenzene's CH3. That's an hour of my life that I would love to save for anyone who tries to manually atomtype their organic molecules in the future (so, approximately two people per decade or thereabouts).

Thank you in advance!!

**Comment by jewettaij** [comment]
Thank you Shern!  I'm sorry you had to suffer.

> That's an hour of my life that I would love to save for anyone who tries to manually atomtype their organic molecules in the future

Yes!  Let's prevent that.

> (so, approximately two people per decade or thereabouts).

I doubt that moltemplate will ever assign atom types or charges automatically.  But other tools do.  Perhaps I could make it easier for moltemplate to work with these tools.  These are the big pain points for moltemplate users (as well as outdated force fields).

Meanwhile I [updated](https://github.com/jewettaij/moltemplate/commit/5364f44e7aee07e75a9d0698252182716f91048a) the description next to that atom type to "Methyl Benzene CH3-"
