### ISSUE TITLE
2.20.21 isn't on https://pypi.org

### ISSUE THREAD

**Issue by yurivict** [jewettaij/moltemplate#106]
https://pypi.org only has 2.20.20 [here](https://pypi.org/project/moltemplate/).

**Comment by jewettaij** [comment]
Thanks Yuri for letting me know.  Fortunately, the changes in 2.20.21 were introduced by Otello and only affect the MOLC force-field.  However I apologize to Otello for not deploying his fix on pypi (or the moltemplate.org website).

Actually, there are several other serious updates that need to be made.  I am making some of them today, and I'll make sure the latest version of moltemplate is on pypi.  (2.20.22, currently.)

**Comment by jewettaij** [comment]
Updated.  Thanks again.
