### ISSUE TITLE
The atomic masses in the TIP5P water model within the OPLSAA2023 force field.

### ISSUE THREAD

**Issue by banbuduo2580** [jewettaij/moltemplate#109]
Thank you very much for your work. I noticed that in the OPLSAA2023 force field file, the atomic mass of the oxygen atom in the TIP5P water model is 32.035, which is the same as the atomic mass of sulfur. Could this be an error in the force field file?
![PixPin_2024-12-06_16-59-03](https://github.com/user-attachments/assets/d65bf698-3b94-46a4-9663-d5b8f238212a)

**Comment by jewettaij** [comment]
Thank you.  Yes.  This is an error.  Also, I never got around to verifying that the TIP5P water model works with OPLSAA.  I removed the TIP5P example (which only worked with the old 2008 version of OPLSAA).

**Comment by jewettaij** [comment]
I am no longer in science, and I no longer have library access to download papers.
I can correct the masses.
If you spot any mistakes in the charges or bond-lengths or angles for these water models, please let me know.

**Comment by jewettaij** [comment]
## More problems with water in OPLSAA 2023:

I don't see any atom types defined for the TIP3P water model.
There's a "TIP3P/F" water atom type, but it has the wrong charges and LJ parameters.  Furthermore, I can't find a reference for this atom type.
So I'll deleting that atom type and replacing it with TIP3P.

**Comment by banbuduo2580** [comment]
Thanks for  responding. If there are any issues, I will provide timely feedback.

**Comment by jewettaij** [comment]
I think I fixed all of the problems with the water models.  (There were a lot of problems.  Not just the mass.)
But more testing is needed.  (This takes a few hours.)
I need to go to bed, but I'll post an update tomorrow with some working TIP5P, TIP3P, SPC/E, and SPC examples.

**Comment by jewettaij** [comment]
This issue was resolved with the release of version 2.22.0 today.
Cheers!

**Comment by banbuduo2580** [comment]
nice,( ゜- ゜)つロ,Cheers!
