### ISSUE TITLE
etree.py line 485 ':' missing at the end of main function definition line.

### ISSUE THREAD

**Issue by edu159** [jewettaij/moltemplate#13]

**Comment by jewettaij** [comment]
Actually both "ettree.py" and "emoltemplate.sh" had bugs.  It looks like they were introduced in late 2016 when I began supporting pip.  I was (apparently) too lazy to test the [ESPResSo examples](https://github.com/jewettaij/emoltemplate).  Version 2.8.2 should finally work with these examples now.
Thanks for catching this Eduardo.
