### ISSUE TITLE
Undefined variable 'needed_improperids'

### ISSUE THREAD

**Issue by andersle** [jewettaij/moltemplate#20]
Hi, I got the following error message while running ``ltemplify.py`` on a system with improper dihedrals:

```bash
File "ltemplify.py", line 3901, in PostProcess3
    for improperid in needed_improperids:
NameError: name 'needed_improperids' is not defined
```

Presumably a ``self.needed_improperids`` is needed on line 3901?

**Comment by jewettaij** [comment]
Thanks again for pointing this out and for the bug fix (PR).  Thanks to you calling attention to it, I also found another similar typo elsewhere.  Hopefully there aren't too many more of these bugs left.  Cheers.
