### ISSUE TITLE
ltemplify.py typo in line 4823

### ISSUE THREAD

**Issue by AJZein** [jewettaij/moltemplate#23]
if len(self.l_data_improper_coeffs) > 0:
                l_data_improper_coeffs.insert(
                    0, (' ' * self.cindent) + 'write_once(\"' + data_improper_coeffs + '\") {')

should be 

            if len(self.l_data_improper_coeffs) > 0:
                self.l_data_improper_coeffs.insert(
                    0, (' ' * self.cindent) + 'write_once(\"' + data_improper_coeffs + '\") {')

**Comment by jewettaij** [comment]
Great catch!
I'm happy to implement the change today.  
But if you want to make your contribution official, I'm happy to accept a pull request from you with this change.  I actually prefer to do this.  If I don't hear back from you by tomorrow, I'll make the change myself.  (We can retroactively do a pull request later if you don't get this message in time.)
Cheers and thanks.

**Comment by jewettaij** [comment]
...Actually, I changed my mind.
Your bug report caused me to notice something else that was also wrong.  (Thanks!)  I'm worried I might forget to fix this if I don't do it today.  So I'm patching the issue now.
    Again, we can do a pull-request retroactively.  I would like to do this if you have time.  (Just add a blank line to the end of the most recent version of "ltemplify.py", issue a pull-request, and I will approve the pull request and add a comment to the commit explaining the real contribution that you made and a link to the relevant commit.)

**Comment by jewettaij** [comment]
Your changes are in commit ce1e34b42395ae8c9251a53e89be4596da3145df, (tag v2.12.8).
Again, if you issue a retroactive pull request, I will approve it.  (See instructions above.) This helps me keep track of who the contributors are.
Thanks again!

closing this issue.

**Comment by AJZein** [comment]
Hi,
Thanks for the offer! I'll take you up on that and add an empty line to the end of the file. Glad to help.
