### ISSUE TITLE
ImportError: No module named moltemplate.lttree_check

### ISSUE THREAD

**Issue by ouening** [jewettaij/moltemplate#38]
After I installed moltemplate in Ubuntu18.04 (python3) and try to run an example from [http://moltemplate.org/visual_examples.html](http://moltemplate.org/visual_examples.html), I got the error as title said. How could I  solve it? Thank you!

**Comment by ouening** [comment]
I tried install it using python2, but I got another problem:
<pre><font color="#859900">╰$ moltemplate.sh</font> <u style="text-decoration-style:single">system.lt</u>
moltemplate.sh v2.18.6 2020-8-13

lttree_check.pyc v0.81.0 2020-3-25
########################################################
##            WARNING: atom_style unspecified         ##
## --&gt; &quot;Data Atoms&quot; column data has an unknown format ##
##              Assuming atom_style = &quot;full&quot;          ##
########################################################

Error at &quot;system.lt&quot;, line 2: 
       unable to open file &quot;ions.lt&quot;
       for reading.
</pre>

**Comment by jewettaij** [comment]
> I tried install it using python2, 

I have both python3 and python2 installed.  However for some people, having multiple different versions of python installed on the same computer causes difficulty for some users.  (Sometimes installing a new version of python causes the previous version to be corrupted.)  This is not specific to moltemplate.

It is also possible that you made a mistake during installation.
What procedure are you using to install moltemplate?

> but I got another problem:
> ╰$ moltemplate.sh system.lt
> Error at "system.lt", line 2: 
>        unable to open file "ions.lt"
>        for reading.

Go to [that web page](http://moltemplate.org/visual_examples.html#waterSPCE+Na+Cl) again, and click on all of the LT files to download them. (spce.lt, ions.lt, system.lt. Also download the "run.in.npt" file.)  Then try again.

*(Incidentally, that example is also located [here](tree/master/examples/all_atom/force_field_explicit_parameters/waterSPCE+Na+Cl))*

Andrew

**Comment by jewettaij** [comment]
The standard way to install moltemplate in ubuntu:

```
sudo apt-get install git python-pip
git clone https://github.com/jewettaij/moltemplate ~/moltemplate
cd ~/moltemplate
pip install .
```

**Comment by jewettaij** [comment]
I haven't heard back from you, so I will assume this fixed your problem.  If not, create another issue, and I will respond to it.
