### ISSUE TITLE
About the   output  the mass information  of   all atoms of the force field  in system.data   for  "all atoms"

### ISSUE THREAD

**Issue by ALEXysd** [jewettaij/moltemplate#52]
Hello！
I found a small problem.I  successfully installed moltemplate on my computer which is windows 10  a few  days ago.After that,I run  a example  on it .Its name is "alkane_chain_single" and  the file path is “examples\all_atom\force_field_OPLSAA\alkane_chain_single”.

I  got the system.data after  running the moltemplate.    Then  I used the VMD to open this file. There was no problem in  molecular configuration  with VMD. But  I found  the mass information  of  all atoms  that own to the force field  in  the system.data  . It seems that this wouldn't  affect  the  consequence  of   simulation. 

I think it will  be  better if the data file  just contains  the  mass information of   the  atoms of given system. Unfortunately  I  haven't learned python and how to use python  yet. So I don't know how to deal with this small problem.I will start to to learn python   and try to address this issue after I finish my current course.And when I'm done, I'll come back and give an answer.

Thank you!

ALEXysd.

**Comment by ALEXysd** [comment]
- [ ]

**Comment by ALEXysd** [comment]
I suddenly find that  jewettaij  had given a way to  solve  this problem.So I decide to close this.
Thank jewettaij ! 
Best wishes to you.

**Comment by jewettaij** [comment]
Hi ALEXysd
    You probably found the "cleanup_moltemplate.sh" script.  That's the way to get around this problem.  Unfortunately, I can imagine [some situations](https://github.com/jewettaij/moltemplate/blob/master/doc/doc_ltemplify.md#exotic-styles-are-not-supported) where this script won't work very well.  (Fortunately, these situations don't effect OPLSAA, DRIEDING, AMBER, or COMPASS users.)  This "cleanup_moltemplate.sh" script is also very slow.  For these reasons I don't run this automatically by default.
   I'm sorry that you had look for the solution to this problem online.  I was hoping people would notice the [README_remove_irrelevant_info.sh](https://github.com/jewettaij/moltemplate/blob/master/examples/all_atom/force_field_OPLSAA/butane/README_remove_irrelevant_info.sh) file.  (Or [this file](https://github.com/jewettaij/moltemplate/tree/master/examples/all_atom/force_field_OPLSAA#bloated-lammps-input-scripts).)  Perhaps I should change the name of these files to make this information easier to find.
Glad you solved your problem.
Andrew
