### ISSUE TITLE
A possible error in the oplsaa force field file

### ISSUE THREAD

**Issue by ALEXysd** [jewettaij/moltemplate#57]
Dear jewettaij：
We can open “oplsaa.lt”  file  in  moltemplate/force_fields.In line 8217,it is "@improper:055_055_X_055 @atom:*_b*_a*_d*_i55 @atom:*_b*_a*_d*_i55 @atom:* @atom:*_b*_a*_d*_i55".  I think  we should use “i055” rather than “i55” in the second half of the sentence .I don’t know if my judgment is correct, but I hope this helps to ensure the correctness of the force field file.
Best wishes.
ALEX

**Comment by jewettaij** [comment]
Thank you very much ALEXysd!
This is definitely a bug.  This line appears to have been added manually into the "oplsaa.lt" file because it does not appear in the [oplsaa.prm](https://dasher.wustl.edu/tinker/distribution/params/oplsaa.prm) file.  I will use git to learn the history of this file and out why this line was added.  Then I will either remove this line or correct it.

I apologize for not replying to your previous question, by the way.  (I have been very busy with my job lately and not getting enough sleep.)  I am glad you are still willing to send bug reports and suggestions.

**Comment by ALEXysd** [comment]
Thank you for your reply!It's okay, this is what I should do. In China, Chairman Mao once said that the body is the capital of the revolution. Please pay attention to rest. Don’t be too tired.I wish you success in your work, and your busy time will pass quickly.

**Comment by jewettaij** [comment]
It looks like those changes to the "oplsaa.lt" file were added in commit [535fc7](https://github.com/jewettaij/moltemplate/commit/535fc757f12b83fed41f66f7c8c7c9e6af204f10), and are legitimate changes.  I changed "i55" to "i055" and posted a new commit with your change.  The newest version of moltemplate should have this change

If you'd like to be one of the moltemplate contributors on github, then feel free to send a pull request with a slight modification to the "oplsaa.lt" file, and I will approve it.  But if this is too much trouble, you don't have to do this.

If you would like to do this, but you don't know how, then:
1) fork moltemplate.  (Log in to github, go to the [moltemplate github page](https://github.com/jewettaij/moltemplate), and click on "fork" button located in the upper-right-hand corner)
2) clone your fork of moltemplate by entering this into the terminal "clone https://github.com/ALEXysd/moltemplate ~/moltemplate_ALEXysd"
3) make a small modification to your version of the "oplsaa.lt" file (add an extra blank line to the end of the file).  It will be in the "~/moltemplate_ALEXysd/moltemplate/force_fields/" directory.
4) Use "cd ~/moltemplate_ALEXysd/", "git add .", "git commit", and "git push origin master" commands to upload your changes to your fork of moltemplate at github
5) Go to your [moltemplate github page](https://github.com/ALEXysd/moltemplate) and issue a [pull-request using github](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)

I will approve the request.  This helps me keep track of who helped me with this project.  But don't bother if you are busy.
Thanks again for your help.

-Andrew

**Comment by jewettaij** [comment]
And thanks for the cool quote!
