### ISSUE TITLE
ERROR: Current temperature too close to zero, consider using ptemp setting (../fix_nh.cpp:788) Last command: run 2000

### ISSUE THREAD

**Issue by vibhuvardhansingh** [jewettaij/moltemplate#58]
In the example file for the Mixture of two organic molecules using the OPLSAA force field (Benzene + Ethylene), the above error is coming after running the command: lmp_serial -i run.in.npt

**Comment by jewettaij** [comment]
Thank you vibhuvardhansingh.
You can get around this issue by adding this line before the "run" command:
```
velocity all create 300.0 12345
```
I will update the examples which use "fix langevin" and "fix nph".
The new version of fix nph wants the velocity of the atoms to be non-zero.
This example used to work, but LAMMPS is always changing.
I really appreciate you reporting this problem.
(I wonder how many others got stuck and gave up.)

**Comment by jewettaij** [comment]
I'll close this issue once I think i have all of the examples updated and tested.
(Sigh.  This will take some time.)

**Comment by vibhuvardhansingh** [comment]
> Thank you vibhuvardhansingh.
> You can get around this issue by adding this line before the "run" command:
> 
> ```
> velocity all create 300.0 12345
> ```
> 
> I will update the examples which use "fix langevin" and "fix nph".
> The new version of fix nph needs the velocity of the atoms to be non-zero.
> I don't know why this problem did not come up earlier, but LAMMPS is always changing.
> I really appreciate you reporting this problem.
> (I wonder how many others got stuck and gave up.)

Yeah now it's working, thanks a lot @jewettaij 
We just need to put that command before `run 2000`

**Comment by jewettaij** [comment]
Hi @vibhuvardhansingh
I think I updated all of the examples which were affected by this problem.  (I did not have time to test all of them after the changes, but they were all very similar, so hopefully everything is working.)
Thanks again for reporting this.
