### ISSUE TITLE
 The number of columns in your data file does not match the LAMMPS atom_style you selected.    

### ISSUE THREAD

**Issue by conandolley103** [jewettaij/moltemplate#64]
Dear Andrew

When I generated the system. data file for the newest version, I got the error " The number of columns in your data file does not match the LAMMPS atom_style you selected. Use the -atomstyle <style> command line argument." However, if I used the version from July 26, 2020, there is no error. Besides, I tested the example files in the old and the newest version, there is also no error. I tried to space between the columns or arrange columns in align but I cannot pass the error. Can you check it? Thank you very much.
Tue Le

**Comment by jewettaij** [comment]
Hi Tue Le

I few days ago I posted an update (v2.20.0) which makes some moderately large changes to the code.  While this new version of moltemplate is able to pass the automated tests I designed, it's possible that I introduced some new bugs.  (On the other hand, 2020-7-26 is a long time ago.)  Either way I take this report seriously.  But I need more information to address this problem.

If you are running into this problem using one of the moltemplate examples, please tell me which one.  On the other hand, if this is a file you created or modified, can you send all of the LT (.lt) files for the system you are trying to build.  (If you are using the -pdb, -xyz, or -raw arguments, then also include those files as well.)  Please tell me the files you used and the steps you used (the commands you typed into the shell) so I can reproduce your problem.

Thanks for reporting.

**Comment by conandolley103** [comment]
Dear Andrew
Here is my file. The problem is only the file name "Chitosan.lt". In the old version, there was no error, but I got the error with the new version. Thank you for considering the error.  

[Chitosan.zip](https://github.com/jewettaij/moltemplate/files/7894766/Chitosan.zip)

**Comment by jewettaij** [comment]
Thanks for sending those files.  The bug was indeed introduced recently.  I think I fixed the bug.  Try the latest version of moltemplate (v2.20.1) and let me know if it helps.  I haven't uploaded it to the moltemplate.org website yet, but you can get it from github.
Reports like yours really help.  Thank you!

**Comment by jewettaij** [comment]
I'm closing this bug.  But if you run into trouble, please reopen it.
Thanks again.
-Andrew
